#Docker for gate
#systemctl start docker
#login: docker login
#build: docker build -f Dockerfile_Gate .
#tag: docker tag <ImageID> tbaudier/cours_jm:v1.0
#push: docker push tbaudier/cours_jm:v1.0
#interactive: docker run -ti --rm -v $PWD:/home tbaudier/cours_jm:v1.0 /bin/bash

FROM python:3.7-slim
SHELL ["/bin/bash", "-c"]
RUN apt-get update -qq \
 && apt-get install -y gcc \
                       g++ \
                       make \
                       binutils \
                       git \
                       cmake \
                       wget \
                       bzip2 \
                       ca-certificates \
                       libglib2.0-0 \
                       libsm6 \
                       libxext6 \
                       libxrender1 \
                       mercurial \
                       subversion \
                       ccache \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

#create folder and install cmake
RUN mkdir software \
 && cd software \
 && wget https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-Linux-x86_64.tar.gz \
 && tar xzvf cmake-3.18.4-Linux-x86_64.tar.gz \
 && rm cmake-3.18.4-Linux-x86_64.tar.gz \
 && echo "export PATH=/software/cmake-3.18.4-Linux-x86_64/bin/:$PATH" >> /root/.profile

#Build root
RUN mkdir software/root-cern \
 && source /root/.profile \
 && cd software/root-cern \
 && mkdir src bin install \
 && git clone --branch v6-19-02 https://github.com/root-project/root.git src \
 && cd bin \
 && cmake ../src/ -Dpython=OFF \
                  -Dx11=OFF \
                  -DCMAKE_INSTALL_PREFIX=/software/root-cern/install \
 && make -j16 install \
 && cd .. \
 && rm -rf bin src

#Build geant4
RUN mkdir software/geant4 \
 && source /root/.profile \
 && cd software/geant4 \
 && mkdir src bin install data \
 && git clone --branch v10.7.0 https://github.com/Geant4/geant4.git src \
 && cd bin \
 && cmake ../src/ -DGEANT4_INSTALL_DATA=OFF \
                  -DGEANT4_INSTALL_DATADIR=/software/geant4/data \
                  -DGEANT4_USE_QT=OFF \
                  -DCMAKE_INSTALL_PREFIX=/software/geant4/install \
                  -DGEANT4_USE_SYSTEM_EXPAT=OFF \
                  -DGEANT4_USE_OPENGL_X11=OFF \
 && make -j16 install \
 && cd .. \
 && rm -rf bin src data

#Download Geant4 data
#Separate to avoid to push large container
RUN cd software/geant4 \
 && mkdir data \
 && wget https://cern.ch/geant4-data/datasets/G4NDL.4.6.tar.gz \
 && tar xzvf G4NDL.4.6.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4EMLOW.7.13.tar.gz \
 && tar xzvf G4EMLOW.7.13.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4PhotonEvaporation.5.7.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4RadioactiveDecay.5.6.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4RealSurface.2.2.tar.gz \
 && tar xzvf G4PhotonEvaporation.5.7.tar.gz \
 && tar xzvf G4RadioactiveDecay.5.6.tar.gz \
 && tar xzvf G4RealSurface.2.2.tar.gz \
 && rm -f G4*.tar.gz \
 && mv PhotonEvaporation5.7 RadioactiveDecay5.6 RealSurface2.2 data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4PARTICLEXS.3.1.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4PII.1.3.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4SAIDDATA.2.0.tar.gz \
 && tar xzvf G4PARTICLEXS.3.1.tar.gz \
 && tar xzvf G4PII.1.3.tar.gz \
 && tar xzvf G4SAIDDATA.2.0.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4ABLA.3.1.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4INCL.1.0.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4ENSDFSTATE.2.3.tar.gz \
 && tar xzvf G4ABLA.3.1.tar.gz \
 && tar xzvf G4INCL.1.0.tar.gz \
 && tar xzvf G4ENSDFSTATE.2.3.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

#Compile Gate
RUN mkdir software/gate \
 && echo "source /software/geant4/install/bin/geant4.sh" >> /root/.profile \
 && echo "source /software/root-cern/install/bin/thisroot.sh" >> /root/.profile \
 && source /root/.profile \
 && cd software/gate \
 && mkdir src bin install \
 && git clone https://github.com/OpenGATE/Gate.git src \
 && cd src \
 && git checkout f02ac64088feef5ff764bb3a57cd605ba9145355 \
 && cd ../bin \
 && cmake ../src -DCMAKE_INSTALL_PREFIX=/software/gate/install \
 && make -j16 install \
 && cd .. \
 && rm -rf src bin \
 && echo "export PATH=/software/gate/install/bin:$PATH" >> /root/.profile

#Change to bash
RUN rm /bin/sh \
 && ln -s /bin/bash /bin/sh

# Leave these args here to better use the Docker build cache
ARG CONDA_VERSION=py38_4.9.2
ARG CONDA_MD5=122c8c9beb51e124ab32a0fa6426c656

# Run miniconda install
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-${CONDA_VERSION}-Linux-x86_64.sh -O miniconda.sh \
 && echo "${CONDA_MD5}  miniconda.sh" > miniconda.md5 \
 && if ! md5sum --status -c miniconda.md5; then exit 1; fi \
 && mkdir -p /opt \
 && sh miniconda.sh -b -p /software/miniconda \
 && rm miniconda.sh miniconda.md5 \
 && find /software/miniconda/ -follow -type f -name '*.a' -delete \
 && find /software/miniconda/ -follow -type f -name '*.js.map' -delete \
 && /software/miniconda/bin/conda clean -afy \
 && echo "export PATH=/software/miniconda/bin:$PATH" >> /root/.profile

 
