#Docker for gate
#systemctl start docker
#login: docker login
#build: docker build -f Dockerfile_Gate .
#tag: docker tag <ImageID> tbaudier/cours_jm:v1.0
#push: docker push tbaudier/cours_jm:v1.0
#interactive: docker run -ti --rm -v $PWD:/home tbaudier/cours_jm:v1.0 /bin/bash

FROM python:3.7-slim
SHELL ["/bin/bash", "-c"]
RUN apt-get update -qq \
 &&   apt-get install -y gcc \
                                  g++ \
                                  make \
                                  binutils \
                                  git \
                                  cmake \
                                  wget \
                                  ccache

#create folder and install cmake
RUN mkdir software \
 && cd software \
 && wget https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-Linux-x86_64.tar.gz \
 && tar xzvf cmake-3.18.4-Linux-x86_64.tar.gz \
 && rm cmake-3.18.4-Linux-x86_64.tar.gz \
 && echo "export PATH=/software/cmake-3.18.4-Linux-x86_64/bin/:$PATH" >> /root/.profile

#Build root
RUN mkdir software/root-cern \
 && source /root/.profile \
 && cd software/root-cern \
 && mkdir src bin install \
 && git clone --branch v6-19-02 https://github.com/root-project/root.git src \
 && cd bin \
 && cmake ../src/ -Dpython=OFF \
                  -Dx11=OFF \
                  -DCMAKE_INSTALL_PREFIX=/software/root-cern/install \
 && make -j16 install \
 && cd .. \
 && rm -rf bin src

#Build geant4
RUN mkdir software/geant4 \
 && source /root/.profile \
 && cd software/geant4 \
 && mkdir src bin install data \
 && git clone --branch v10.7.0 https://github.com/Geant4/geant4.git src \
 && cd bin \
 && cmake ../src/ -DGEANT4_INSTALL_DATA=OFF \
                  -DGEANT4_INSTALL_DATADIR=/software/geant4/data \
                  -DGEANT4_USE_QT=OFF \
                  -DCMAKE_INSTALL_PREFIX=/software/geant4/install \
                  -DGEANT4_USE_SYSTEM_EXPAT=OFF \
                  -DGEANT4_USE_OPENGL_X11=OFF \
 && make -j16 install \
 && cd .. \
 && rm -rf bin src data

#Download Geant4 data
#Separate to avoid to push large container
RUN cd software/geant4 \
 && mkdir data \
 && wget https://cern.ch/geant4-data/datasets/G4NDL.4.6.tar.gz \
 && tar xzvf G4NDL.4.6.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4EMLOW.7.13.tar.gz \
 && tar xzvf G4EMLOW.7.13.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4PhotonEvaporation.5.7.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4RadioactiveDecay.5.6.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4RealSurface.2.2.tar.gz \
 && tar xzvf G4PhotonEvaporation.5.7.tar.gz \
 && tar xzvf G4RadioactiveDecay.5.6.tar.gz \
 && tar xzvf G4RealSurface.2.2.tar.gz \
 && rm -f G4*.tar.gz \
 && mv PhotonEvaporation5.7 RadioactiveDecay5.6 RealSurface2.2 data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4PARTICLEXS.3.1.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4PII.1.3.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4SAIDDATA.2.0.tar.gz \
 && tar xzvf G4PARTICLEXS.3.1.tar.gz \
 && tar xzvf G4PII.1.3.tar.gz \
 && tar xzvf G4SAIDDATA.2.0.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4ABLA.3.1.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4INCL.1.0.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4ENSDFSTATE.2.3.tar.gz \
 && tar xzvf G4ABLA.3.1.tar.gz \
 && tar xzvf G4INCL.1.0.tar.gz \
 && tar xzvf G4ENSDFSTATE.2.3.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

#Compile Gate
RUN mkdir software/gate \
 && echo "cd /software/geant4/install/bin/" >> /root/.profile \
 && echo "source ./geant4.sh" >> /root/.profile \
 && echo "cd /software/root-cern/install/bin/" >> /root/.profile \
 && echo "source ./thisroot.sh" >> /root/.profile \
 && echo "cd /" >> /root/.profile \
 && source /root/.profile \
 && cd software/gate \
 && mkdir src bin install \
 && git clone https://github.com/OpenGATE/Gate.git src \
 && cd src \
 && git checkout f02ac64088feef5ff764bb3a57cd605ba9145355 \
 && cd ../bin \
 && cmake ../src -DCMAKE_INSTALL_PREFIX=/software/gate/install \
 && make -j16 install \
 && cd .. \
 && rm -rf src bin \
 && echo "export PATH=/software/gate/install/bin:$PATH" >> /root/.profile

